kind = "web"
previewPath = "/"
title = "eyedriveguide"
version = "1.0.0"
id = "new-mvc-solution-base-001"

[[services]]
localPort = 8080
name = "eyedriveguide"
paths = ["/"]

[services.development]
run = "dotnet run --project /home/runner/workspace/eyedriveguide/eyedriveguide/eyedriveguide.csproj --urls http://0.0.0.0:8080"
